# =========================================
# Stage: Development
# =========================================
ARG NODE_VERSION=24.18-alpine3.23

FROM node:${NODE_VERSION} AS dev

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .
 
# Ensure the "node" user owns the application files
RUN chown -R node:node /app

USER node

EXPOSE 5173

# Run Vite in dev mode, accessible outside the container
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]