// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID          pgtype.UUID
	OriginalUrl string
	ShortCode   string
	CreatedAt   pgtype.Timestamptz
	ClickCount  int32
}
