// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Url struct {
	ID          uuid.UUID
	OriginalUrl string
	ShortCode   string
	CreatedAt   time.Time
	ExpiresAt   time.Time
	UpdatedAt   time.Time
	ClickCount  int32
}
