// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (original_url, short_code, created_at, expires_at, updated_at)
VALUES ($1, $2, now(), $3, now())
RETURNING id, original_url, short_code, created_at, expires_at, updated_at, click_count
`

type CreateURLParams struct {
	OriginalUrl string
	ShortCode   string
	ExpiresAt   time.Time
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL, arg.OriginalUrl, arg.ShortCode, arg.ExpiresAt)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
		&i.ClickCount,
	)
	return i, err
}

const getURL = `-- name: GetURL :one
SELECT id, original_url, short_code, created_at, updated_at, expires_at
FROM urls 
WHERE short_code = $1
`

type GetURLRow struct {
	ID          uuid.UUID
	OriginalUrl string
	ShortCode   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ExpiresAt   time.Time
}

func (q *Queries) GetURL(ctx context.Context, shortCode string) (GetURLRow, error) {
	row := q.db.QueryRowContext(ctx, getURL, shortCode)
	var i GetURLRow
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteURL = `-- name: deleteURL :exec
DELETE FROM urls
WHERE short_code = $1
`

func (q *Queries) deleteURL(ctx context.Context, shortCode string) error {
	_, err := q.db.ExecContext(ctx, deleteURL, shortCode)
	return err
}

const getURLStats = `-- name: getURLStats :one
SELECT id, original_url, short_code, created_at, expires_at, updated_at, click_count FROM urls
WHERE short_code = $1
`

func (q *Queries) getURLStats(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLStats, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
		&i.ClickCount,
	)
	return i, err
}

const updateOriginalURL = `-- name: updateOriginalURL :one
UPDATE urls
SET original_url = $1, updated_at = $2
WHERE short_code = $3
RETURNING original_url, short_code, created_at, updated_at, expires_at
`

type updateOriginalURLParams struct {
	OriginalUrl string
	UpdatedAt   time.Time
	ShortCode   string
}

type updateOriginalURLRow struct {
	OriginalUrl string
	ShortCode   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ExpiresAt   time.Time
}

func (q *Queries) updateOriginalURL(ctx context.Context, arg updateOriginalURLParams) (updateOriginalURLRow, error) {
	row := q.db.QueryRowContext(ctx, updateOriginalURL, arg.OriginalUrl, arg.UpdatedAt, arg.ShortCode)
	var i updateOriginalURLRow
	err := row.Scan(
		&i.OriginalUrl,
		&i.ShortCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
