// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (original_url, short_code)
VALUES ($1, $2)
RETURNING short_code
`

type CreateURLParams struct {
	OriginalUrl string
	ShortCode   string
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (string, error) {
	row := q.db.QueryRow(ctx, createURL, arg.OriginalUrl, arg.ShortCode)
	var short_code string
	err := row.Scan(&short_code)
	return short_code, err
}

const getURL = `-- name: GetURL :one
SELECT original_url
FROM urls 
WHERE short_code = $1
`

func (q *Queries) GetURL(ctx context.Context, shortCode string) (string, error) {
	row := q.db.QueryRow(ctx, getURL, shortCode)
	var original_url string
	err := row.Scan(&original_url)
	return original_url, err
}

const getURLStats = `-- name: GetURLStats :one
SELECT click_count, created_at
FROM urls
WHERE short_code = $1
`

type GetURLStatsRow struct {
	ClickCount int32
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetURLStats(ctx context.Context, shortCode string) (GetURLStatsRow, error) {
	row := q.db.QueryRow(ctx, getURLStats, shortCode)
	var i GetURLStatsRow
	err := row.Scan(&i.ClickCount, &i.CreatedAt)
	return i, err
}

const incrementClickCount = `-- name: IncrementClickCount :exec
UPDATE urls
SET click_count = click_count + 1
WHERE short_code = $1
`

func (q *Queries) IncrementClickCount(ctx context.Context, shortCode string) error {
	_, err := q.db.Exec(ctx, incrementClickCount, shortCode)
	return err
}
