// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (original_url, short_code, expires_at)
VALUES ($1, $2, $3)
RETURNING original_url, short_code, created_at, expires_at
`

type CreateURLParams struct {
	OriginalUrl string
	ShortCode   string
	ExpiresAt   pgtype.Timestamptz
}

type CreateURLRow struct {
	OriginalUrl string
	ShortCode   string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (CreateURLRow, error) {
	row := q.db.QueryRow(ctx, createURL, arg.OriginalUrl, arg.ShortCode, arg.ExpiresAt)
	var i CreateURLRow
	err := row.Scan(
		&i.OriginalUrl,
		&i.ShortCode,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getURL = `-- name: GetURL :one
SELECT id, original_url, short_code, created_at, expires_at
FROM urls 
WHERE short_code = $1
`

type GetURLRow struct {
	ID          pgtype.UUID
	OriginalUrl string
	ShortCode   string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) GetURL(ctx context.Context, shortCode string) (GetURLRow, error) {
	row := q.db.QueryRow(ctx, getURL, shortCode)
	var i GetURLRow
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getURLStats = `-- name: GetURLStats :one
SELECT click_count, created_at, expires_at
FROM urls
WHERE short_code = $1
`

type GetURLStatsRow struct {
	ClickCount int32
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) GetURLStats(ctx context.Context, shortCode string) (GetURLStatsRow, error) {
	row := q.db.QueryRow(ctx, getURLStats, shortCode)
	var i GetURLStatsRow
	err := row.Scan(&i.ClickCount, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}
