name: frontend-ci

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"

  pull_request:
    branches: ["main"]

jobs:
  changes:
    name: Frontend Changes
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            frontend:
              - "frontend/**"

  tests:
    name: Frontend Tests
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up NodeJS
        uses: actions/setup-node@v7
        with:
          node-version-file: frontend/.nvmrc
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Run clean install
        run: npm ci

      - name: Run tests
        run: npm test

  quality:
    name: Frontend Code Quality
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up NodeJS
        uses: actions/setup-node@v7
        with:
          node-version-file: frontend/.nvmrc
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Run clean install
        run: npm ci

      - name: Run format checker
        run: npm run format-check

      - name: Run linter
        run: npm run lint
